#!/usr/bin/env python3

import sys
import decoder


# remove the first which is the program name
sys.argv.pop(0)

for i in sys.argv:
    bs = bytes.fromhex(i)
    mem = None
    freq = None
    if len(bs) == 3:
        mem=decoder.frequency.decode(bs)
        freq = mem
    elif len(bs) == 4:
        mem=decoder.channel.decode(bs)
        freq = mem.freq
    ffreq = str(mem)
    if freq.unused:
        ffreq += f" ({freq.freq})" 
    print(f"{bs.hex()}  => {ffreq}")
