#!/usr/bin/env python3

import sys
import decoder


# remove the first which is the program name
sys.argv.pop(0)

for i in sys.argv:
    bs = bytes.fromhex(i)
    mem = None
    if len(bs) == 3:
        mem=decoder.frequency.decode(bs)
    elif len(bs) == 4:
        mem=decoder.channel.decode(bs)
    print(bs.hex() + " => " + str(mem))
